# Generated by Django 5.0.6 on 2024-11-11 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
